PReMaSys/Models/SERecord.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Security.Policy;
using PReMaSys.Data;

namespace PReMaSys.Models
{
    public class SERecord
    {
        [Key]
        public int SEmployeeRecordsID { get; set; }

        public ApplicationUser?  SERId { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Employee No.")]
        public string? EmployeeNo { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Employee First Name")]
        public string? EmployeeFirstname { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Employee Last Name")]
        public string? EmployeeLastname { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Employee Address")]
        public string? EmployeeAddress { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Employee Birthdate")]
        public string? EmployeeBirthdate { get; set; }


        [Range(0, 10000000000, ErrorMessage = "Must be a valid number!")]
        [Display(Name = "Employee Points")]
        public string? EmployeePoints { get; set; }

        [Display(Name = "Date Added")]
        public DateTime DateAdded { get; set; }

        [Display(Name = "Date Modified")]
        public DateTime? DateModified { get; set; }
    }
}

PReMaSys/Controllers/SupportAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using PReMaSys.Data;
using PReMaSys.Models;
using PReMaSys.ViewModel;
using System.Data;
using System.Linq;

namespace PReMaSys.Controllers
{
    [Authorize(Roles = "Support")]
    public class SupportAdminController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public SupportAdminController(RoleManager<IdentityRole> roleManager, ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _context = context;
            _userManager = userManager;
        }

        public IActionResult SupportPage() //Good
        {
            return View();
        }
        public IActionResult NotificationPage() //Good
        {
            ApplicationUser user = _context.ApplicationUsers.FirstOrDefault(u => u.Id == _userManager.GetUserId(HttpContext.User));

            var list = _context.Purchase.ToList();
            return View(list);
        }

        public IActionResult EditStatus(int? id) //Good
        {
            if (id == null)
            {
                return RedirectToAction("NotificationPage");
            }

            //variable product that retrieves the existing record from the Rewards table.
            var status = _context.Purchase.Where(r => r.PurchaseId == id).SingleOrDefault();

            //if the reward record is not present the view will redirect to the Index action.
            if (status == null)
            {
                return RedirectToAction("IndexSE");
            }

            //Rewards model object will be included to be rendered by the View method
            return View(status);
        }

        [HttpPost]
        public IActionResult EditStatus(int? id, Purchase record) //Good
        {
            var status = _context.Purchase.Where(s => s.PurchaseId == id).SingleOrDefault();

            status.EmployeeName = record.EmployeeName;
            status.RewardName = record.RewardName;
            status.Stat = record.Stat;
            status.DateModified = DateTime.Now;
            _context.Purchase.Update(status);
            _context.SaveChanges();

            return RedirectToAction("NotificationPage");
        }



        /*New Methods*/
        public IActionResult EmployeeRole() //Good
        {
            var roles = _roleManager.Roles;

            return View(roles);
        }

        [HttpGet]
        public IActionResult ListSalesEmployee() //Good
        {
            ApplicationUser user = _context.ApplicationUsers.FirstOrDefault(u => u.Id == _userManager.GetUserId(HttpContext.User));
            var list = _context.Users.Where(c => c.user == user).ToList();
            return View(list);
        }

        /*EDIT ADMIN ROLES Account------------------------------------------------*/
        [HttpGet]
        public async Task<IActionResult> EditSalesLC(string id) //Good
        {
            var se = await _userManager.FindByIdAsync(id);

            if (se == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }

            var userClaims = await _userManager.GetClaimsAsync(se);
            var userRoles = await _userManager.GetRolesAsync(se);

            var model = new EditSalesUserViewModel
            {
                Id = se.Id,
                Email = se.Email,
                UserName = se.UserName,
                /*Claims = User.Claims.Select(c => c.Value).ToList(),*/
                Roles = userRoles
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditSalesLC(EditSalesUserViewModel model) //Good
        {
            var se = await _userManager.FindByIdAsync(model.Id);

            if (se == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                se.UserName = model.Email;
                se.Email = model.Email;
                var result = await _userManager.UpdateAsync(se);
                if (result.Succeeded)
                {
                    return RedirectToAction("ListSalesEmployee");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }

        //DELETE ADMIN ACCOUNT
        public async Task<IActionResult> DeleteSLC(string id) //Good
        {            
            var se = await _userManager.FindByIdAsync(id);

            /*var check = _context.SERecord.FirstOrDefault(s => s.SERId == se).SEmployeeRecordsID;
            rec = _context.SERecord.FirstOrDefault(r => r.SEmployeeRecordsID == check);*/

            /*var check = _context.SERecord.FirstOrDefault(s => s.SERId == se).SEmployeeRecordsID;*/
            var emp = _context.SERecord.Where(s => s.SERId == se).SingleOrDefault();

            if (User == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }
            else
            {
                var result = await _userManager.DeleteAsync(se);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListSalesEmployee");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                
                _context.SERecord.Remove(emp);
                _context.SaveChanges();

                return View("ListAdminRoles");              
            }
        }


        /*CREATE NEW ADMIN ROLE*/
        public IActionResult SERecord() //Good
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> SERecord(SalesUser se) //Good
        {
            
            ApplicationUser userz = _context.ApplicationUsers.FirstOrDefault(u => u.Id == _userManager.GetUserId(HttpContext.User));

            var user = new ApplicationUser
            {
                UserName = se.Email,
                Email = se.Email,
                EmailConfirmed = true,
                user = userz,

            };
            if (se.Password == se.ConfirmPassword)
            {
                var insertrec = await _userManager.CreateAsync(user, se.Password);
                if (insertrec.Succeeded)
                {
                    TempData["ResultMessage"] = "The User \t " + se.Email + "\tIs Saved Succesfully..!!";
                }
                else
                {
                    foreach (var error in insertrec.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            else
            {
                TempData["ResultMessage2"] = "Password Mismatch";
            }

            var latest = user.Id;
            var getId = _context.ApplicationUsers.FirstOrDefault(u => u.Id == latest);
            var userzz = new SERecord   
            {
               /* SERId = latest,*/
                SERId = getId,
                EmployeeNo = se.EmployeeNo,
                EmployeeFirstname = se.EmployeeFirstname,
                EmployeeLastname = se.EmployeeLastname,
                EmployeeAddress = se.EmployeeAddress,
                EmployeeBirthdate = se.EmployeeBirthdate,
            };
            _context.SERecord.Add(userzz);
            _context.SaveChanges();

            return View();
        }
  
       
        /*REWARDS CRUD--------------------------------------------------------------------------------------------------------------------------------------------------------*/
        public IActionResult RewardsRecord() //Good
        {
            ApplicationUser user = _context.ApplicationUsers.FirstOrDefault(u => u.Id == _userManager.GetUserId(HttpContext.User));
            var list = _context.Rewards.Where(c => c.ApplicationUser == user).ToList();
            return View(list);
        }

        //(1) Create Reward Information
        public IActionResult CreateR() //Good
        {
            return View();
        }

        //Overriding exising Create method through Replica
        [HttpPost]
        public IActionResult CreateR(Rewards record, IFormFile Picture) //Good
        {
            ApplicationUser user = _context.ApplicationUsers.FirstOrDefault(u => u.Id == _userManager.GetUserId(HttpContext.User));
            var rewards = new Rewards()
            {
                ApplicationUser = user,
                RewardName = record.RewardName,
                Description = record.Description,
                RewardCost = record.RewardCost,
                PointsCost = record.PointsCost,
                DateAdded = DateTime.Now,
                Category = record.Category,
                Status = record.Status,
            };

            if (Picture != null)
            {
                if (Picture.Length > 0)
                {
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/rewards", Picture.FileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        Picture.CopyTo(stream);
                    }
                    rewards.Picture = "~/img/rewards/" + Picture.FileName;
                }
            }

PReMaSys/Views/SupportAdmin/CreateR.cshtml
@model PReMaSys.Models.Rewards

@{
    ViewData["Title"] = "Create Rewards";
    Layout = "~/Views/Shared/SupportAdminDash.cshtml";
}

<h1 class="text-center mt-4">Create Rewards</h1>

<h4 class="text-center mb-4">Rewards</h4>
<hr />
         <form asp-action="CreateR" class="create-r-form mt-5" enctype="multipart/form-data">
            <div class="form-group  mb-3">
               @* <label asp-for="Picture" class="control-label"></label>*@
                <input asp-for="Picture" class="form-control" type="file" accept="file/*" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group  mb-3">
               @* <label asp-for="RewardName" class="control-label"></label>*@
                <input asp-for="RewardName" placeholder="Reward Name" class="form-control" />
                <span asp-validation-for="RewardName" class="text-danger"></span>
            </div>
            <div class="form-group  mb-3">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="Category" class="form-control"
                        asp-items="Html.GetEnumSelectList<Category>()" required></select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group  mb-3">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group  mb-3">
               @* <label asp-for="RewardCost" class="control-label"></label>*@
                <input asp-for="RewardCost" placeholder="Reward Cost" class="form-control" type="number" min="0" max="10000000000"/>
                <span asp-validation-for="RewardCost" class="text-danger"></span>
            </div>
            <div class="form-group  mb-3">
               @* <label asp-for="PointsCost" class="control-label"></label>*@
                <input asp-for="PointsCost" placeholder="Point Cost"class="form-control"  type="number" min="0" max="100000000000"/>
                <span asp-validation-for="PointsCost" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 mt-5">
                <input type="submit" value="Create" class="btn btn-success" />
                  <a asp-action="RewardsRecord" class="btn btn-outline-success">Back to List</a>
            </div>
        </form>
 
       

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

PReMaSys/Views/SupportAdmin/EditR.cshtml
@model PReMaSys.Models.Rewards

@{
    ViewData["Title"] = "EditR";
    Layout = "~/Views/Shared/SupportAdminDash.cshtml";
}

<div class="container">

<h1 class="text-center mt-5">EditR</h1>
<h4 class="text-center mb-4">Rewards</h4>
<hr />
        <form asp-action="EditR" class="edit-r-form mt-5">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RewardsInformationId" />
            <div class="form-group mb-3">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="RewardName" class="control-label"></label>
                <input asp-for="RewardName" class="form-control" />
                <span asp-validation-for="RewardName" class="text-danger"></span>
            </div>
            <div class="form-group  mb-3">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="Category" class="form-control" asp-items="Html.GetEnumSelectList<Category>()"></select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group  mb-3">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group  mb-3">
                <label asp-for="RewardCost" class="control-label"></label>
                <input asp-for="RewardCost" class="form-control" />
                <span asp-validation-for="RewardCost" class="text-danger"></span>
            </div>
            <div class="form-group  mb-3">
                <label asp-for="PointsCost" class="control-label"></label>
                <input asp-for="PointsCost" class="form-control" />
                <span asp-validation-for="PointsCost" class="text-danger"></span>
            </div>
            <div class="form-group  mb-3  mt-5">
                <input type="submit" value="Save" class="btn btn-success" />
                 <a asp-action="RewardsRecord" class="btn btn-outline-success">Back to List</a>
            </div>
        </form>
  

</div>

PReMaSys/Views/SupportAdmin/EditSalesLC.cshtml
@model PReMaSys.ViewModel.EditSalesUserViewModel

@{
    ViewBag.Title = "Edit Sales Log-in Credentials";
}

<h1 class="text-center mt-5 mb-5">Edit Sales Log-in Credentials</h1>

<form asp-action="EditSalesLC" asp-controller="SupportAdmin" method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" disabled class="form-control" />
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10 mt-4">
            <button type="submit" class="btn btn-success">Update</button>
            <a asp-action="ListSalesEmployee" class="btn btn-secondary"> Cancel</a>

        </div>
    </div>
    <div class="card mt-5">
        <div class="card-header">
            <h3>User Roles</h3>
        </div>
        <div class="card-body">
            @if (Model.Roles.Any())
            {
                foreach (var role in Model.Roles)
                {
                    <h5 class="card-title">@role</h5>
                }
            }
            else
            {
                <h5 class="card-title">None at the moment</h5>
            }
           @* <div class="card-footer">
                <a href="#" style="width:auto" class="btn btn-primary">Manage Roles</a>

            </div>*@
        </div>
    </div>
</form>

PReMaSys/Views/SupportAdmin/EditStatus.cshtml
@model PReMaSys.Models.Purchase

@{
    ViewData["Title"] = "EditStatus";
}

<h1>EditStatus</h1>

<h4>Purchase</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="SupportAdmin" asp-action="EditStatus">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PurchaseId" />
            <div class="form-group">
                <label asp-for="EmployeeName" class="control-label"></label>
                <input asp-for="EmployeeName" class="form-control" />
                <span asp-validation-for="EmployeeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RewardImage" class="control-label"></label>
                <input asp-for="RewardImage" class="form-control" />
                <span asp-validation-for="RewardImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RewardName" class="control-label"></label>
                <input asp-for="RewardName" class="form-control" />
                <span asp-validation-for="RewardName" class="text-danger"></span>
            </div>
            <div class="form-group  mb-3">
                <label asp-for="Stat" class="control-label"></label>
                <select asp-for="Stat" class="form-control" asp-items="Html.GetEnumSelectList<Stat>()"></select>
                <span asp-validation-for="Stat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="NotificationPage">Back to List</a>
</div>

PReMaSys/Views/SupportAdmin/EmployeeRole.cshtml
@using Microsoft.AspNetCore.Identity;
@model IEnumerable<IdentityRole>
@{
    ViewData["Title"] = "EmployeeRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Sales Employee Role</h1>

@if (Model.Any())
{
    @foreach (var role in Model)
    {
        if (role.Name.Contains("Sales"))
        {
            <div class="card mb-3">
                <div class="card-header">
                    Role Id: @role.Id
                </div>
                <div class="card-body">
                    <h5 class="card-title">@role.Name</h5>
                </div>
                <div class="footer" style="padding:20px">
                    <a asp-controller="Manage" asp-action="EditRole" asp-route-id="@role.Id" class="btn btn-primary btn-sm"> Assign Role</a>
@*                    <a asp-controller="Manage" asp-action="DeleteRole" asp-route-id="@role.Id" class="btn btn-danger btn-sm"> Delete Role</a>*@
                </div>
            </div>
            <a asp-controller="SupportAdmin" asp-action="ListSalesEmployee" class="btn btn-danger"> Go Back </a>
        }
    }
}
else
{
    <div class="card">
        <div class="card-header">
            No Roles Created Yet
        </div>
    </div>
}

PReMaSys/Views/SupportAdmin/IndexR.cshtml
@model IEnumerable<PReMaSys.Models.Rewards>

@{
    ViewData["Title"] = "IndexR";
    Layout = "~/Views/Shared/SupportAdminDash.cshtml";
}

<div class="container">

<h1 class="text-center mt-5 mb-5">Index</h1>

    <a asp-action="CreateR" class="btn btn-success p-2 mb-3 d-inline-block" >Create New +</a>

<div class="table-responsive">
<table class="table table-hover" id=datatable>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Picture)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RewardName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RewardCost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PointsCost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateAdded)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateModified)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4" style="color:red; font-family:'Franklin Gothic Book'"> No rows match the Search Criteria!</td>
            </tr>
        }
        else
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <img style="height:2em" src="@Url.Content(item.Picture)" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RewardName)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Category)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RewardCost)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PointsCost)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateAdded)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateModified)
                    </td>
                    <td>
                        <a asp-action="EditR" asp-route-id="@item.RewardsInformationId" class="btn btn-info"><i class="fa-regular fa-pen-to-square"></i></a>
                        <a asp-action="DeleteR" asp-route-id="@item.RewardsInformationId" class="btn btn-danger" onclick='return confirm("Are You Sure?");'><i class="fa-regular fa-trash-can"></i></a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>


<script src="https://code.jquery.com/jquery-3.5.1.js"></script>"
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
<script>
    $(document).ready(function () {
    $('#datatable').DataTable();
});
</script>
</div>
<a class="notificationback-link btn btn-outline-success p-2 mt-5" href="SupportPage" type="button">Back</a>

</div>

PReMaSys/Views/SupportAdmin/ListSalesEmployee.cshtml
@model IEnumerable<PReMaSys.Data.ApplicationUser>
@{
    ViewData["Title"] = "List Sales Employee";
     Layout = "~/Views/Shared/SupportAdminDash.cshtml";
}

<h1 class="text-center mt-5">Sales Employee List </h1>

<div class="ms-5 mt-5">
 <a asp-action="SERecord" asp-controller="SupportAdmin" class="btn btn-success p-2 mb-3">Add New Sales Employee + </a>
 @*<a asp-action="EmployeeRole" asp-controller="SupportAdmin" class="btn btn-success p-2  mb-3">Assign Role</a>*@
</div>

@if (Model.Any())
{
    foreach (var user in Model)
    {
      <div class="px-5 mt-3">
        <div class="card">
            <div class="card-header">
                User Id :@user.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">@user.UserName</h5>
            </div>
            <div class="card-footer">
                <form asp-action="DeleteSLC" asp-route-id="@user.Id" method="post">
                    <a asp-action="EmployeeRole" asp-controller="SupportAdmin" class="btn btn-success p-2  mb-3">Assign Role</a>
                    <a asp-controller="SupportAdmin" asp-action="EditSalesLC" asp-route-id="@user.Id" class="btn btn-outline-success">Edit</a>
                    <button type="submit" class="btn btn-outline-danger" onlick="deleteFunct()">Delete</button>
                </form>
            </div>
        </div>
      </div>
    }
    <a asp-action="SupportPage" class="btn btn-outline-success ms-5 mt-5">Go Back</a>
}

<script>
    function deleteFunct() {
        alert("Are you sure to delete?, Delete Message");
    }
</script>

PReMaSys/Views/SupportAdmin/SERecord.cshtml
@model PReMaSys.Models.SalesUser

@{
    ViewData["Title"] = "SERecord";
     Layout = "~/Views/Shared/SupportAdminDash.cshtml";
}

<div class="container">
  <h1 class="text-center mt-5 mb-5">Sales Employee Credentials</h1>
    <h5 class="text-success">@TempData["ResultMessage"]</h5><h5 class="text-danger">@TempData["ResultMessage2"]</h5>
        <form asp-action="SERecord" class="se-record-form" asp-controller="SupportAdmin" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3 mt-3">
               @* <label asp-for="Email" class="control-label"></label>*@
                <input asp-for="EmployeeNo" placeholder="EmployeeNo" class="form-control" required />
                <span asp-validation-for="EmployeeNo" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 mt-3">
               @* <label asp-for="Email" class="control-label"></label>*@
                <input asp-for="EmployeeFirstname" placeholder="EmployeeFirstname" class="form-control" required />
                <span asp-validation-for="EmployeeFirstname" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 mt-3">
               @* <label asp-for="Email" class="control-label"></label>*@
                <input asp-for="EmployeeLastname" placeholder="EmployeeLastname" class="form-control" required />
                <span asp-validation-for="EmployeeLastname" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 mt-3">
               @* <label asp-for="Email" class="control-label"></label>*@
                <input asp-for="EmployeeAddress" placeholder="EmployeeAddress" class="form-control" required/>
                <span asp-validation-for="EmployeeAddress" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 mt-3">
               @* <label asp-for="Email" class="control-label"></label>*@
                <input asp-for="EmployeeBirthdate" placeholder="EmployeeBirthdate" class="form-control" required />
                <span asp-validation-for="EmployeeBirthdate" class="text-danger"></span>
            </div>

            <div class="form-group mb-3 mt-3">
               @* <label asp-for="Email" class="control-label"></label>*@
                <input asp-for="Email" placeholder="Email" class="form-control" type="email" required />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                @*<label asp-for="Password" class="control-label"></label>*@
                <input asp-for="Password" placeholder="Password" class="form-control" required />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
               @* <label asp-for="ConfirmPassword" class="control-label"></label>*@
                <input asp-for="ConfirmPassword" placeholder="Confirm Password" class="form-control" required/>
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 mt-4">
                <input type="submit" value="Employee Record" class="btn btn-success" required />
                  <a asp-action="ListSalesEmployee" class="btn btn-outline-success">Back to List</a>
            </div>
           
        </form>

</div>

PReMaSys/Views/SupportAdmin/SupportPage.cshtml
@{
    ViewData["Title"] = "SupportPage";
    Layout = "~/Views/Shared/SupportAdminDash.cshtml";
}

  <div class="performance-options-container">
   <div class=" mt-5 mt-md-0">
    <h1 class="text-center mb-5">Support Page</h1>
    <div class="performance-options main-pg-card-whole-support  w-lg-50 w-100">
      <div class="mainpg-card-first-support option-link text-center border border-success rounded p-3 ">
           <a class="option-text" href="~/SupportAdmin/ListSalesEmployee">
          <h3>Sales Employee Records</h3>    
          <img src="~/img/roleadminpic.png" class="img-fluid mainpage-usrs-pic" />
        </a>
        </div>
        <div class="mainpg-card option-link text-center border border-success rounded p-3">
            <a class="option-text last" href="~/SupportAdmin/RewardsRecord">
          <h3>Rewards Records</h3>
          <img src="~/img/rewardspic.png" class="img-fluid mainpage-usrs-pic"/>
        </a>
        </div>
      </div>
    </div>
</div>